### PR TITLE
Updated the Quickstart documentation

### PR DESCRIPTION
**Pull request by YohannFaure**
I changed the documentation of the quickstart, as we discussed by email.

### CODE REVIEW

**Comment by fredRos** [comment]
close or merge?

**Comment by YohannFaure** [comment]
I think you should merge, I modified the quickstart example to make it more understandable for a begginer, and more up to date according to the recent evolution of EMCEE.

**Comment by mtazzari** [comment]
I cannot push to YohannFaure/galario:master. I've opened #175 where I can do so.

**Comment by mtazzari** [comment]
Closing this, continuing on #175

**Pull request closed without merging**
