### PR TITLE
chi2 functions

### PR DESCRIPTION
**Pull request by fredRos**
* refactor code to return chi2 directly instead of through a pointer argument
* check that visibilities are not modified inside `reduce_chi2`

### CODE REVIEW

**Comment by fredRos** [comment]
@mtazzari I addressed your comment and replace `ints` in many places where you had put it. 
Whenever you or I review a PR, we have to make sure that changes to the functionality or the interface are reflected in the docs. I had not done it before but did it with my last commit.

**Comment by fredRos** [comment]
Still to be tested on the GPU

**Comment by mtazzari** [comment]
All tests pass on GPU, however `ctest -V --gpu` or `ctest -V --gpu=1` do not execute the tests on GPU.
To run them I had to 
```bash
cd build
cd python
py.test -v --gpu=1 test_galario.py
```

**Comment by fredRos** [comment]
Yes, that's what our section on tests in the installation instructions say:

        make && python/py.test.sh -sv --gpu=1 python_package/tests/test_galario.py

**Comment by mtazzari** [comment]
There are so many ways of running these tests! I never use `py.test.sh` for example..

**Pull request merged**
